#!/usr/bin/env bash

# https://github.com/NixOS/nix.dev/blob/master/source/tutorials/nixos/building-bootable-iso-image.md

NIX_PATH=https://github.com/NixOS/nixpkgs/archive/refs/tags/23.11.tar.gz nix-shell -p nixos-generators --run "nixos-generate --format iso --configuration ./plasma-image.nix -o result"
