--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/erik/.config/variety/Downloaded/wallhaven_space/wallhaven-x6ejll.jpg"

-- Special
background="#0a0604"
foreground="#b0a2c5"
cursor="#b0a2c5"

-- Colors
color0="#0a0604"
color1="#41304D"
color2="#504C4C"
color3="#6C605D"
color4="#86563D"
color5="#8F6D56"
color6="#AC8C6F"
color7="#b0a2c5"
color8="#7b7189"
color9="#41304D"
color10="#504C4C"
color11="#6C605D"
color12="#86563D"
color13="#8F6D56"
color14="#AC8C6F"
color15="#b0a2c5"
