# Shell variables
# Generated by 'wal'
wallpaper='/home/erik/.config/variety/Downloaded/wallhaven_minimal/wallhaven-qzjxvl.png'

# Special
background='#050513'
foreground='#98b3d7'
cursor='#98b3d7'

# Colors
color0='#050513'
color1='#0C358B'
color2='#0C349F'
color3='#0E4794'
color4='#0E52AC'
color5='#1E63B1'
color6='#1270C9'
color7='#98b3d7'
color8='#6a7d96'
color9='#0C358B'
color10='#0C349F'
color11='#0E4794'
color12='#0E52AC'
color13='#1E63B1'
color14='#1270C9'
color15='#98b3d7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
