--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/erik/.config/variety/Downloaded/wallhaven_minimal/wallhaven-qzjxvl.png"

-- Special
background="#050513"
foreground="#98b3d7"
cursor="#98b3d7"

-- Colors
color0="#050513"
color1="#0C358B"
color2="#0C349F"
color3="#0E4794"
color4="#0E52AC"
color5="#1E63B1"
color6="#1270C9"
color7="#98b3d7"
color8="#6a7d96"
color9="#0C358B"
color10="#0C349F"
color11="#0E4794"
color12="#0E52AC"
color13="#1E63B1"
color14="#1270C9"
color15="#98b3d7"
