#!/bin/bash
#set -e
##################################################################################################################
# Author    : Erik Dubois
# Website   : https://www.erikdubois.be
# Website   : https://www.alci.online
# Website   : https://www.arcolinux.info
# Website   : https://www.arcolinux.com
# Website   : https://www.arcolinuxd.com
# Website   : https://www.arcolinuxb.com
# Website   : https://www.arcolinuxiso.com
# Website   : https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
#tput setaf 0 = black 
#tput setaf 1 = red 
#tput setaf 2 = green
#tput setaf 3 = yellow 
#tput setaf 4 = dark blue 
#tput setaf 5 = purple
#tput setaf 6 = cyan 
#tput setaf 7 = gray 
#tput setaf 8 = light blue
##################################################################################################################

echo "###############################################################################"
echo "Switch qwerty config  with azerty config"
echo "###############################################################################"
echo

user=$( who | cut -d ' ' -f1 | uniq)

cp -v /home/$user/.config/hypr/hyprland-azerty.conf /home/$user/.config/hypr/hyprland.conf

echo
echo "###############################################################################"
echo "Switch to mirrored screens"
echo "###############################################################################"
echo

FIND="monitor=,preferred,auto,auto"
REPLACE="#monitor=,preferred,auto,auto"
sudo sed -i "s/$FIND/$REPLACE/g" /home/$user/.config/hypr/hyprland.conf

# monitor=HDMI-A-1,1920x1080@60,0x0,1,mirror,HDMI-A-2
#FIND="# monitor=HDMI-A-1,1920x1080@60,0x0,1,mirror,HDMI-A-2"
#REPLACE="monitor=HDMI-A-1,1920x1080@60,0x0,1,mirror,HDMI-A-2"
#sudo sed -i "s/$FIND/$REPLACE/g" /home/$user/.config/hypr/hyprland.conf

# monitor=,preferred,auto,1,mirror,HDMI-A-1
#FIND="# monitor=,preferred,auto,1,mirror,HDMI-A-1"
#REPLACE="monitor=,preferred,auto,1,mirror,HDMI-A-1"
#sudo sed -i "s/$FIND/$REPLACE/g" /home/$user/.config/hypr/hyprland.conf


echo
echo "###############################################################################"
echo "###                         and that is that                               ####"
echo "###                              reboot                                    ####"
echo "###############################################################################"
