#!/usr/bin/env bash
#set -e
##################################################################################################################
# Author    : Erik Dubois
# Website   : https://www.erikdubois.be
# Website   : https://www.alci.online
# Website   : https://www.ariser.eu
# Website   : https://www.arcolinux.info
# Website   : https://www.arcolinux.com
# Website   : https://www.arcolinuxd.com
# Website   : https://www.arcolinuxb.com
# Website   : https://www.arcolinuxiso.com
# Website   : https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
#tput setaf 0 = black
#tput setaf 1 = red
#tput setaf 2 = green
#tput setaf 3 = yellow
#tput setaf 4 = dark blue
#tput setaf 5 = purple
#tput setaf 6 = cyan
#tput setaf 7 = gray
#tput setaf 8 = light blue
##################################################################################################################

installed_dir=$(dirname $(readlink -f $(basename `pwd`)))

##################################################################################################################

path="/home/erik/Documents/nixos-configurations/"
host=$(hostname)

cd $path

echo
tput setaf 2
echo "################################################################"
echo "################### Git pull on "$host
echo "################################################################"
tput sgr0
echo

git pull

cd dotfiles
bash ./copy.sh

if [ $host == "nixos-riker" ]; then
	echo
	tput setaf 2
	echo "################################################################"
	echo "################### Copy over config for "$host
	echo "################################################################"
	tput sgr0
	echo

	cd $path/riker
	bash ./copy.sh
	cd ..
fi

if [ $host == "nixos-data" ]; then
	echo
	tput setaf 2
	echo "################################################################"
	echo "################### Copy over config for "$host
	echo "################################################################"
	tput sgr0
	echo

	cd $path/data
	bash ./copy.sh
	cd ..
fi


if [ $host == "nixos-worf" ]; then
	echo
	tput setaf 2
	echo "################################################################"
	echo "################### Copy over config for "$host
	echo "################################################################"
	tput sgr0
	echo

	cd $path/worf
	bash ./copy.sh
	cd ..
fi


if [ $host == "nixos-picard" ]; then
	echo
	tput setaf 2
	echo "################################################################"
	echo "################### Copy over config for "$host
	echo "################################################################"
	tput sgr0
	echo

	cd $path/picard
	bash ./copy.sh
	cd ..
fi

sudo nix-collect-garbage --delete-older-than 30d
