#!/usr/bin/env bash

picom -b --config ~/.config/picom.conf &

$HOME/.config/polybar/launch.sh &

#bluetooth#
#(blueberry-tray) &

numlockx &

## GNOME PolicyKit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Desktop notification
/usr/lib/xfce4/notifyd/xfce4-notifyd &

## Volume control for systray
(volumeicon) &


## Turn off/on System Beep
xset b off

(nm-applet) &

(plank) &
