#!/usr/bin/env bash

# Terminate already running instances
killall -q swaybg

# Wait until the processes have been shut down
while pgrep -x swaybg >/dev/null; do sleep 1; done

random_wallpaper=$(find ~/.local/share/wallpapers/ -type f | sort -R | head -1)

swaybg -m fill -i $random_wallpaper &
