#!/usr/bin/env bash

herbstclient emit_hook reload

# KEYBINDINGS

# remove all existing keybindings
herbstclient keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1  # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# herbstclient keybind $Mod-Shift-x quit
# herbstclient keybind $Mod-Shift-r reload
# herbstclient keybind $Mod-Shift-q close
# herbstclient keybind $Mod-q close

#Most of the keybindings have been set in sxhkd config file
#you can set them also here

#reload sxhkd - see keybind in sxhkd
#herbstclient keybind $Mod-Shift-s  pkill -USR1 -x sxhkd

# MOVEMENTS

# focusing clients
herbstclient keybind $Mod-Left  focus left
herbstclient keybind $Mod-Down  focus down
herbstclient keybind $Mod-Up    focus up
herbstclient keybind $Mod-Right focus right
herbstclient keybind $Mod-h     focus left
herbstclient keybind $Mod-j     focus down
herbstclient keybind $Mod-k     focus up
herbstclient keybind $Mod-l     focus right

# moving clients to ... on single Monitor
herbstclient keybind $Mod-Shift-Left  shift left
herbstclient keybind $Mod-Shift-Down  shift down
herbstclient keybind $Mod-Shift-Up    shift up
herbstclient keybind $Mod-Shift-Right shift right
herbstclient keybind $Mod-Shift-h     shift left
herbstclient keybind $Mod-Shift-j     shift down
herbstclient keybind $Mod-Shift-k     shift up
herbstclient keybind $Mod-Shift-l     shift right

# moving clients to ... on dual monitor
# herbstclient keybind $Mod-Shift-h chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# herbstclient keybind $Mod-Shift-Left chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# herbstclient keybind $Mod-Shift-j chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# herbstclient keybind $Mod-Shift-Down chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
# herbstclient keybind $Mod-Shift-k chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
# herbstclient keybind $Mod-Shift-Up chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
# herbstclient keybind $Mod-Shift-l chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
# herbstclient keybind $Mod-Shift-Right chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# FRAMES

# create an empty frame at the specified direction
herbstclient keybind $Mod-u       split   bottom  0.5
herbstclient keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
herbstclient keybind $Mod-Control-space split explode
# remove frame
herbstclient keybind $Mod-r remove

# resizing frames
resizestep=0.05
herbstclient keybind $Mod-Control-h       resize left +$resizestep
herbstclient keybind $Mod-Control-j       resize down +$resizestep
herbstclient keybind $Mod-Control-k       resize up +$resizestep
herbstclient keybind $Mod-Control-l       resize right +$resizestep
herbstclient keybind $Mod-Control-Left    resize left +$resizestep
herbstclient keybind $Mod-Control-Down    resize down +$resizestep
herbstclient keybind $Mod-Control-Up      resize up +$resizestep
herbstclient keybind $Mod-Control-Right   resize right +$resizestep

# TAGS or WORKSPACES

#names to display in menu
#tag_names=( {1..10} )
#tag_names=("Web" "Chat" "Edit" "Meld" "Vb" "Mail" "Video" "Image" "Files" "Music")
tag_names=("I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")

#keys to press to get to the tags
#Qwerty
#tag_keys=( {1..10} 0 )

#Belgian azerty
tag_keys=( ampersand eacute quotedbl apostrophe parenleft section egrave exclam ccedilla agrave )

#French azerty
#tag_keys=( ampersand eacute quotedbl apostrophe parenleft minus egrave underscore ccedilla agrave )

#Discord tip for some keyboards
#tag_keys=( "1" "2" "3" "4" "5" "6" "7" "8" "9" "0" )

herbstclient rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    herbstclient add "${tag_names[$i]}"
    # horizontal tiling as standard
    herbstclient set_layout horizontal
    herbstclient set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        herbstclient keybind "$Mod-$key" use_index "$i"
        herbstclient keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
    fi
done

# layouting
herbstclient keybind $Mod-s floating toggle
herbstclient keybind $Mod-f fullscreen toggle
herbstclient keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
herbstclient keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max grid    \
               , cycle_layout +1

# mouse
herbstclient mouseunbind --all
herbstclient mousebind $Mod-Button1 move
herbstclient mousebind $Mod-Button2 zoom
herbstclient mousebind $Mod-Button3 resize

# focus on ...
herbstclient keybind $Mod-BackSpace   cycle_monitor
herbstclient keybind $Mod-Tab         use_index +1 --skip-visible
herbstclient keybind $Mod-Shift-Tab   use_index -1 --skip-visible
herbstclient keybind Control-Mod1-Left    focus left
herbstclient keybind Control-Mod1-Up      focus up
herbstclient keybind Control-Mod1-Right   focus right
herbstclient keybind Control-Mod1-Down    focus down
herbstclient keybind Mod1-Tab         use_index +1 --skip-visible
herbstclient keybind Mod1-Shift-Tab   use_index -1 --skip-visible
#herbstclient keybind $Mod-c cycle
herbstclient keybind $Mod-i jumpto urgent

#reset prior to setting the theme
herbstclient attr theme.reset 1

# Attribute
herbstclient attr theme.active.color '#6790EB'
herbstclient attr theme.active.inner_color '#141414'
herbstclient attr theme.active.outer_color '#6790EB'
herbstclient attr theme.background_color '#141414'
herbstclient attr theme.border_width 3
herbstclient attr theme.floating.border_width 4
herbstclient attr theme.floating.outer_width 1
herbstclient attr theme.floating.outer_color black
herbstclient attr theme.inner_color black
herbstclient attr theme.inner_width 1
herbstclient attr theme.normal.color '#141414'
herbstclient attr theme.urgent.color orange

# Set
herbstclient set always_show_frame 1
herbstclient set focus_follows_mouse 1
herbstclient set frame_border_active_color '#6790EB'
herbstclient set frame_border_normal_color '#141414'
herbstclient set frame_bg_normal_color '#141414'
herbstclient set frame_bg_active_color '#000000'
herbstclient set frame_border_width 3
herbstclient set frame_bg_transparent 1
herbstclient set frame_transparent_width 0
herbstclient set frame_gap 5
herbstclient set frame_padding 0
herbstclient set mouse_recenter_gap 0
herbstclient set smart_frame_surroundings 1
herbstclient set smart_window_surroundings 0
herbstclient set tree_style '╾│ ├└╼─┐'
herbstclient set window_gap 5


# RULES
herbstclient unrule -F
herbstclient rule focus=on # normally focus new clients
#herbstclient rule focus=off # normally do not focus new clients

# assign applications to workspaces or tags -using numbers for tags
# These are used then -- tag_names=( {1..10} )

# herbstclient rule class~'(Navigator|Firefox|Vivaldi-stable|Vivaldi-snapshot|Chromium|Google-chrome|Brave|Brave-browser)' tag=1 switchtag=on focus=on
# herbstclient rule class~'(navigator|firefox|vivaldi-stable|vivaldi-snapshot|chromium|google-chrome|brave|brave-browser)' tag=1 switchtag=on focus=on
# herbstclient rule class~'(Atom|Subl|Geany|Brackets|Code-oss|Code|TelegramDesktop|Discord)' tag=2 switchtag=on focus=on
# herbstclient rule class~'(atom|subl|geany|brackets|code-oss|code|telegramdesktop|discord)' tag=2 switchtag=on focus=on
# herbstclient rule class~'(Inkscape|Nomacs|Ristretto|Nitrogen|Feh)' tag=3 switchtag=on focus=on
# herbstclient rule class~'(inkscape|nomacs|ristretto|nitrogen|feh)' tag=3 switchtag=on focus=on
# herbstclient rule class~'(Gimp)' tag=4 switchtag=on focus=on
# herbstclient rule class~'(gimp)' tag=4 switchtag=on focus=on
# herbstclient rule class~'(Meld|org.gnome.Meld)' tag=5 switchtag=on focus=on
# herbstclient rule class~'(meld|org.gnome.meld)' tag=5 switchtag=on focus=on
# herbstclient rule class~'(Vlc|Mpv)' tag=6 switchtag=on focus=on
# herbstclient rule class~'(vlc|mpv)' tag=6 switchtag=on focus=on
# herbstclient rule class~'(VirtualBox Manager|VirtualBox Machine|Vmplayer)' tag=7 switchtag=on focus=on
# herbstclient rule class~'(virtualbox manager|virtualbox machine|vmplayer)' tag=7 switchtag=on focus=on
# herbstclient rule class~'(Thunar|Nemo|Caja|Nautilus|org.gnome.Nautilus|Pcmanfm|Pcmanfm-qt)' tag=8 switchtag=on focus=on
# herbstclient rule class~'(thunar|nemo|caja|nautilus|org.gnome.nautilus|pcmanfm|pcmanfm-qt)' tag=8 switchtag=on focus=on
# herbstclient rule class~'(Evolution|Geary|Mail|Thunderbird)' tag=9 switchtag=on focus=on
# herbstclient rule class~'(evolution|geary|mail|thunderbird)' tag=9 switchtag=on focus=on
# herbstclient rule class~'(Spotify|Pragha|Clementine|Deadbeef|Audacious)' tag=10 switchtag=on focus=on
# herbstclient rule class~'(spotify|pragha|clementine|deadbeef|audacious)' tag=10 switchtag=on focus=on

# assign applications to workspaces or tags - using names for tags
# These are used then -- #tag_names=("Web" "Chat" "Edit" "Meld" "Vb" "Mail" "Video" "Image" "Files" "Music")

# herbstclient rule class~'(Navigator|Firefox|Vivaldi-stable|Vivaldi-snapshot|Chromium|Google-chrome|Brave|Brave-browser)' tag='Web' switchtag=on focus=on
# herbstclient rule class~'(navigator|firefox|vivaldi-stable|vivaldi-snapshot|chromium|google-chrome|brave|brave-browser)' tag='Web' switchtag=on focus=on
# herbstclient rule class~'(TelegramDesktop|Discord)' tag='Chat' switchtag=on focus=on
# herbstclient rule class~'(telegramdesktop|discord)' tag='Chat' switchtag=on focus=on
# herbstclient rule class~'(Atom|Subl|Geany|Brackets|Code-oss|Code)' tag='Edit' switchtag=on focus=on
# herbstclient rule class~'(atom|subl|geany|brackets|code-oss|code)' tag='Edit' switchtag=on focus=on
# herbstclient rule class~'(Inkscape|Nomacs|Ristretto|Nitrogen|Feh)' tag='Image' switchtag=on focus=on
# herbstclient rule class~'(inkscape|nomacs|ristretto|nitrogen|feh)' tag='Image' switchtag=on focus=on
# herbstclient rule class~'(Gimp)' tag='Image' switchtag=on focus=on
# herbstclient rule class~'(gimp)' tag='Image' switchtag=on focus=on
# herbstclient rule class~'(Meld|org.gnome.Meld)' tag='Meld' switchtag=on focus=on
# herbstclient rule class~'(meld|org.gnome.meld)' tag='Meld' switchtag=on focus=on
# herbstclient rule class~'(Vlc|Mpv)' tag='Video' switchtag=on focus=on
# herbstclient rule class~'(vlc|mpv)' tag='Video' switchtag=on focus=on
# herbstclient rule class~'(VirtualBox Manager|VirtualBox Machine|Vmplayer)' tag='Vb' switchtag=on focus=on
# herbstclient rule class~'(virtualbox manager|virtualbox machine|vmplayer)' tag='Vb' switchtag=on focus=on
# herbstclient rule class~'(Thunar|Nemo|Caja|Nautilus|org.gnome.Nautilus|Pcmanfm|Pcmanfm-qt)' tag='Files' switchtag=on focus=on
# herbstclient rule class~'(thunar|nemo|caja|nautilus|org.gnome.nautilus|pcmanfm|pcmanfm-qt)' tag='Files' switchtag=on focus=on
# herbstclient rule class~'(Evolution|Geary|Mail|Thunderbird)' tag='Mail' switchtag=on focus=on
# herbstclient rule class~'(evolution|geary|mail|thunderbird)' tag='Mail' switchtag=on focus=on
# herbstclient rule class~'(Spotify|Pragha|Clementine|Deadbeef|Audacious)' tag='Music' switchtag=on focus=on
# herbstclient rule class~'(spotify|pragha|clementine|deadbeef|audacious)' tag='Music' switchtag=on focus=on

# give focus to most common terminals
#herbstclient rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
#herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient rule class=Oblogout fullscreen=on
herbstclient rule class=Insync pseudotile=on
herbstclient rule class=VirtualBox fullscreen=on
#herbstclient rule class=Archlinux-tweak-tool.py pseudotile=on
herbstclient rule class=Arcolinux-welcome-app.py pseudotile=on
herbstclient rule class=Arcolinux-calamares-tool.py pseudotile=on
herbstclient rule windowrole=xfce4-terminal-dropdown floating=on

# unlock, just to be sure
herbstclient unlock

#Dualmonitor setup
# Find out your monitor name with xrandr or arandr (save and you get this line)
#xrandr --output VGA-1 --primary --mode 1360x768 --pos 0x0 --rotate normal
#xrandr --output DP2 --primary --mode 1920x1080 --rate 60.00 --output LVDS1 --off &
#xrandr --output LVDS1 --mode 1366x768 --output DP3 --mode 1920x1080 --right-of LVDS1
#xrandr --output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off

#Dualmonitor setup
# herbstclient detect_monitors
# xrandr in a terminal and copy/paste your resolution in
# Determine a sane resolution for Linux guests.
# check if more than one screen
# count=$(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l)
# # sane defaults
# local X_RES=1152
# local Y_RES=648
# if [ "${XDG_SESSION_TYPE}" == "x11" ]; then
#   X_RES=$(xrandr --listmonitors | grep -v Monitors | cut -d' ' -f4 | cut -d'/' -f1 | sort | head -n1)
#   Y_RES=$(xrandr --listmonitors | grep -v Monitors | cut -d' ' -f4 | cut -d'/' -f2 | cut -d'x' -f2 | sort | head -n1)
# fi
  
# if [ $count -gt 1 ]; then
#   herbstclient set_monitors $X_RES"x"$Y_RES"+0+0" $X_RES"x"$Y_RES"+"$X_RES"+0"
# fi

#room for polybar on both monitors
#single polybar at top
herbstclient pad 0 30
#second polybar at bottom
#herbstclient pad 0 30 0 30 0
#single polybar at top
herbstclient pad 1 30
#second polybar at bottom
#herbstclient pad 1 30 0 30 0

#launching polybar
#~/.config/herbstluftwm/polybar/launch.sh

#change your keyboard if you need it
#setxkbmap -layout be

# #Autostart applications
# pkill -u $USER '^picom$'
# picom  --config $HOME/.config/herbstluftwm/picom.conf &

# xsetroot -solid '#000000'
# xsetroot -cursor_name left_ptr &

# #keybindings are in config of sxhkd - interchangeable with other TWM
# sxhkd -c ~/.config/herbstluftwm/sxhkd/sxhkdrc &

# run variety &
# nm-applet &
# numlockx on &
# blueberry-tray &
# run volumeicon &
