static const char black[]       = "#2E3440";
static const char gray2[]       = "#3B4252"; // unfocused window border
static const char gray3[]       = "#606672";
static const char gray4[]       = "#262626";
static const char blue[]        = "#6d8dad";
static const char green[]       = "#54976E";  // focused window border
static const char lightgreen[]  = "#89b482";
static const char red[]         = "#BF616A";
static const char orange[]      = "#caaa6a";
static const char yellow[]      = "#EBCB8B";
static const char purple[]      = "#B48EAD";
static const char col_borderbar[]  = "#2E3440"; // inner border
