#!/usr/bin/env bash

# https://github.com/NixOS/nix.dev/blob/master/source/tutorials/nixos/building-bootable-iso-image.md
# https://nix.dev/tutorials/nixos/building-bootable-iso-image.html

NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/74e2faf5965a12e8fa5cff799b1b19c6cd26b0e3.tar.gz nix-shell -p nixos-generators --run "nixos-generate --format iso --configuration ./minimal-image.nix -o result"